task1. Функция, суммирующая два числа
js-tasks-ru/jsbasic-20201113_ev410 pull request #1
Opened 2020-11-22 17:23 UTC by Alena410

2020-11-22 17:51 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Первая задача
+ 1+1=2
```

Добавляю преподавателя (@koalex) для код-ревью, посмотрим что он скажет :)

2020-11-22 20:59 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-11-24 06:44 UTC, koalex requested changes
Исправь замечание

2020-11-24 06:44 UTC, koalex commented on 1-module/1-task/index.js
> +	alert(`Задано не натуральное число`);
строки 19 - 24 удали

2020-11-24 09:42 UTC, koalex approved these changes

2020-11-24 09:42 UTC, jsru commented
PR не может быть принят, обратитесь, пожалуйста, к преподавателю.

2020-11-24 09:46 UTC, koalex requested changes
Тебе нужно решить [1 модуль 4 таск](https://github.com/js-tasks-ru/jsbasic-20201113_ev410/tree/master/1-module/4-task) чтобы PR прошёл. Если ты добавила какую-то задачу, то ты должна её решить иначе PR не пройдёт

2020-11-24 10:26 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Первая задача
+ 1+1=2
```
```diff
Вычислить факториал
+ факториал 1 равен 1
+ факториал 3 равен 6 
+ факториал 0 равен 1
+ факториал 5 равен 120 
```
```diff
Допишите функцию валидации имени пользователя
+ если меньше 4 символов то false
+ если имя корректное, то true
+ если содержит пробелы, то false
```
```diff
Сделать первый символ заглавным
+ должна делать первый символ заглавным
+ должна работать для строки из одной буквы
+ должна работать для пустой строки
```
```diff
Проверка на спам
- должна возвращать false для 'innocent rabbit'
- должна возвращать true для 'free xxxxx'
- должна возвращать true для '1XbeT now'
```

2020-11-24 11:12 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Вычислить факториал
+ факториал 5 равен 120 
+ факториал 1 равен 1
+ факториал 3 равен 6 
+ факториал 0 равен 1
```
```diff
Первая задача
+ 1+1=2
```
```diff
Допишите функцию валидации имени пользователя
+ если меньше 4 символов то false
+ если содержит пробелы, то false
+ если имя корректное, то true
```
```diff
Сделать первый символ заглавным
+ должна работать для строки из одной буквы
+ должна делать первый символ заглавным
+ должна работать для пустой строки
```
```diff
Усечение строки
- должна не трогать короткую строку 
- должна усекать строку 
```
```diff
Проверка на спам
+ должна возвращать false для 'innocent rabbit'
+ должна возвращать true для '1XbeT now'
+ должна возвращать true для 'free xxxxx'
```

2020-11-24 11:58 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Сделать первый символ заглавным
+ должна делать первый символ заглавным
+ должна работать для строки из одной буквы
+ должна работать для пустой строки
```
```diff
Первая задача
+ 1+1=2
```
```diff
Проверка на спам
+ должна возвращать true для '1XbeT now'
+ должна возвращать true для 'free xxxxx'
+ должна возвращать false для 'innocent rabbit'
```
```diff
Допишите функцию валидации имени пользователя
+ если содержит пробелы, то false
+ если меньше 4 символов то false
+ если имя корректное, то true
```
```diff
Усечение строки
- должна усекать строку 
- должна не трогать короткую строку 
```
```diff
Вычислить факториал
+ факториал 5 равен 120 
+ факториал 1 равен 1
+ факториал 3 равен 6 
+ факториал 0 равен 1
```

2020-11-24 12:42 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Усечение строки
- должна усекать строку 
- должна не трогать короткую строку 
```
```diff
Проверка на спам
+ должна возвращать true для 'free xxxxx'
+ должна возвращать false для 'innocent rabbit'
+ должна возвращать true для '1XbeT now'
```
```diff
Первая задача
+ 1+1=2
```
```diff
Сделать первый символ заглавным
+ должна работать для пустой строки
+ должна делать первый символ заглавным
+ должна работать для строки из одной буквы
```
```diff
Допишите функцию валидации имени пользователя
+ если имя корректное, то true
+ если меньше 4 символов то false
+ если содержит пробелы, то false
```
```diff
Вычислить факториал
+ факториал 0 равен 1
+ факториал 1 равен 1
+ факториал 3 равен 6 
+ факториал 5 равен 120 
```

2020-11-24 13:53 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-11-24 15:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-11-25 07:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-11-25 08:19 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Определите, пуст ли объект
+ объект со свойством undefined должен считаться не пустым
+ {} должен вернуть true
+ если у объекта есть хоть одно свойство, то он не пустой
+ объект с удалённым свойством - пустой
```
```diff
Сделать первый символ заглавным
+ должна работать для строки из одной буквы
+ должна делать первый символ заглавным
+ должна работать для пустой строки
```
```diff
Проверка на спам
+ должна возвращать true для 'free xxxxx'
+ должна возвращать false для 'innocent rabbit'
+ должна возвращать true для '1XbeT now'
```
```diff
Функция sumSalary(salaries)
+ должна возвращать 0 если нет свойств с зарплатами
+ должна игнорировать свойства других типов
+ должна складывать все зарплаты
```
```diff
Создайте калькулятор
- должно умножать числа
- должно складывать числа
```
```diff
Первая задача
+ 1+1=2
```
```diff
Усечение строки
+ должна усекать строку 
+ должна не трогать короткую строку 
```
```diff
Допишите функцию валидации имени пользователя
+ если имя корректное, то true
+ если меньше 4 символов то false
+ если содержит пробелы, то false
```
```diff
Вычислить факториал
+ факториал 5 равен 120 
+ факториал 3 равен 6 
+ факториал 0 равен 1
+ факториал 1 равен 1
```

2020-11-25 09:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-11-26 11:40 UTC, koalex approved these changes

2020-11-26 11:41 UTC, merged